
train_data: "HRNNdata_en/train.pkl"
validation_data: "HRNNdata_en/val.pkl"

embedding-flag: Bert
embedding-path: "embeddings"
sentences-files:
 - "data/en_new_notation_ground_truths/test.txt"
embedding_token_heuristic: "mean"
bert_pretrained_weights: "bert-large-cased"
embedding_dim: 1024
device: gpu
train_embeddings: embeddings/2023-11-21_13:01:45.899918/embeddings.ebd.pt
validation_embeddings: embeddings/2023-11-21_13:01:45.899918/embeddings.ebd.pt
experiments-path: "experiments"

learning_rate: 2.0e-05
epocs: 1
warmup: 0